# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.9'

services:
  dotnetangular:
    image: dotnetangular
    build:
      context: .
      dockerfile: Dotnet.Angular/Dockerfile
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  dotnetangular-alpine:
    image: dotnetangular-alpine
    build:
      context: .
      dockerfile: Dotnet.Angular/Dockerfile.alpine
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
